# Generated by Django 5.2.17 on 2026-09-19 12:42

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_display_name', models.CharField(default='Sahabat Menabung', max_length=50)),
                ('currency_symbol', models.CharField(default='Rp', max_length=10)),
                ('date_format', models.CharField(default='DD/MM/YYYY', max_length=20)),
                ('reminder_enabled', models.BooleanField(default=True)),
                ('reminder_time', models.TimeField(default='20:00:00')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon_name', models.CharField(default='savings', max_length=50)),
                ('color_theme', models.CharField(choices=[('blue', 'Sky Cyan (#7FCFFF)'), ('emerald', 'Mint Green (#6DD58C)'), ('violet', 'Lavender (#D0BCFF)'), ('amber', 'Warm Gold (#FFD270)'), ('rose', 'Soft Coral (#FFB4AB)')], default='blue', max_length=20)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('current_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('currency', models.CharField(default='IDR', max_length=10)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('target_date', models.DateField()),
                ('period_frequency', models.CharField(choices=[('DAILY', 'Harian'), ('WEEKLY', 'Mingguan'), ('MONTHLY', 'Bulanan')], default='DAILY', max_length=20)),
                ('planned_amount_per_period', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('ACHIEVED', 'Tercapai'), ('CANCELLED', 'Dibatalkan')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavingsReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('frequency', models.CharField(choices=[('DAILY', 'Harian'), ('WEEKLY', 'Mingguan'), ('MONTHLY', 'Bulanan')], default='DAILY', max_length=20)),
                ('reminder_time', models.TimeField(default='20:00:00')),
                ('is_active', models.BooleanField(default=True)),
                ('last_notified_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='savings.savingsgoal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Tambah (+ Setor)'), ('WITHDRAW', 'Kurang (- Tarik)')], default='DEPOSIT', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('transaction_date', models.DateField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='savings.savingsgoal')),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
