# Generated by Django 5.2.17 on 2026-09-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_alter_savingsgoal_target_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='goals/'),
        ),
    ]
