# Generated by Django 5.2.17 on 2026-09-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0003_savingsgoal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='image_ratio',
            field=models.CharField(blank=True, choices=[('1:1', 'Kotak (1:1)'), ('4:3', 'Landscape (4:3)'), ('3:4', 'Portrait (3:4)'), ('16:9', 'Widescreen (16:9)')], default='4:3', max_length=10),
        ),
    ]
